
build:
	dmd matEngine.d -L"-rpath=/home/rrau/MATLAB/R2015b/bin/glnxa64" -L-L"/home/rrau/MATLAB/R2015b/bin/glnxa64" -L-lpthread -L-lmx -L-lmex -L-lmat -L-lm -L-lstdc++ -L-leng -g
	#gdc matEngine.d -o matEngine -Wl,-rpath=/home/rrau/MATLAB/R2015b/bin/glnxa64 -L/home/rrau/MATLAB/R2015b/bin/glnxa64 -lpthread -lmx -lmex -lmat -lm -lstdc++ -leng -g